version: '3'

services:
  db:
    container_name: ws-db
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: